set guioptions-=T		" remove toolbar
set guioptions-=m		" remove menu bar
let s:os = substitute(system('uname'), "\n", "", "")

if s:os == "Darwin"
    set guifont=Menlo\ Regular:h16
elseif s:os == "Linux"
    set guifont=Monospace\ 13
endif


set background=light
colorscheme solarized

set lines=30
set columns=100

set number

set statusline=%F%M%R%H%W\ %y[%{&ff}][%{&fenc}]\ [charcode:\ \%03.3bd/\%02.2Bh]\ [pos:\ %04l,%03v\ (%p%%\*%L)]

set clipboard=unnamed
