set guioptions-=T		" remove toolbar
set guioptions-=m		" remove menu bar

let s:os = substitute(system('uname'), "\n", "", "")

if s:os == "Darwin"
    set guifont=Menlo\ Regular:h16
elseif s:os == "Linux"
    set guifont=DejaVu\ Sans\ Mono\ 16
endif

set background=light
colorscheme solarized

set lines=30
set columns=100

set number

set statusline=%F%M%R%H%W\ %y[%{&ff}][%{&fenc}]\ [charcode:\ \%03.3bd/\%02.2Bh]\ [pos:\ %04l,%03v\ (%p%%\*%L)]

set clipboard=unnamed

let g:indent_guides_guide_size = 1
let g:indent_guides_start_level = 2

let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#fdf6e3
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#eee8d5

IndentGuidesEnable
