call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

syntax on

set nocompatible

set ls=2

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set scrolloff=3

set showcmd

set title
set ttyfast

set modeline
set modelines=3

set incsearch

set cursorline

filetype plugin on
filetype plugin indent on

if filereadable($HOME."/.vim/vimrc/vimrc-local.vim")
    source ~/.vim/vimrc/vimrc-local.vim
endif
